name: DIVA_APT Backend AI CI/CD Pipeline

on:
  push:
    branches:
      - main
      - cicd-test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SERVER_USERNAME: ${{ secrets.SERVER_USERNAME}}
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
      SERVER_SSH_PORT: ${{ secrets.SERVER_SSH_PORT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Java 17 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # SSH key, SCP 설치
      - name: Install SSH key and SCP tools
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client
          echo $SERVER_SSH_KEY > private_key
          chmod 600 private_key

      # 빌드에 포함되는 필수 리소스 파일 다운로드
      - name: Download necessary file
        run: |
          scp -P $SERVER_PORT -i private_key -r $SERVER_USERNAME@$SERVER_IP:/home/$SERVER_USERNAME/server/resources src/main

      # jar 빌드
      - name: Build application with Gradle
        run: ./gradlew clean build

      # 원격 서버로 jar 파일 업로드 (with scp)
      - name: Copy jar file to remote server
        uses: appleboy/scp-action@master
        with:
            host: ${{ env.SERVER_IP }}
            username: ${{ env.SERVER_USERNAME }}
            key: ${{ env.SERVER_SSH_KEY }}
            port: ${{ env.SERVER_SSH_PORT }}
            source: "build/libs/diva_apt_ai.jar"
            target: "/home/$SERVER_USERNAME/server"

      # AI 모델 레포 최신화
      - name: Refresh AI model repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USERNAME }}
          key: ${{ env.SERVER_SSH_KEY }}
          port: ${{ env.SERVER_SSH_PORT }}
          script: |
            cd
            if [ -d "/home/${SERVER_USERNAME}/diva-dataprep" ]; then
              git clone https://github.com/DIVA-APT/diva-dataprep
            else
              cd diva-dataprep
              git pull origin main
              cd
            fi
            

      # 배포 (daemon)
      - name: Deploy application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USERNAME }}
          key: ${{ env.SERVER_SSH_KEY }}
          port: ${{ env.SERVER_SSH_PORT }}
          script: |
            sudo systemctl restart diva-spring